controllers:
    resource: ../../src/Controller/
    type: annotation
    prefix:
        fr-FR: '' # don't prefix URLs for the default locale
        en-US: 'en'

kernel:
    resource: ../../src/Kernel.php
    type: annotation
