controllers:
    resource: ../../src/Controller/
    type: annotation
    prefix:
        fr: '' # don't prefix URLs for the default locale
        en: 'en'

kernel:
    resource: ../../src/Kernel.php
    type: annotation
