name: Docker image

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - name: Build the Docker images
      run:  |
        docker build --pull -t "tomcraftmc/fsalist:nginx-${GITHUB_REF##*/}" -f ./docker/nginx/Dockerfile .
        docker build --pull -t "tomcraftmc/fsalist:php-fpm-${GITHUB_REF##*/}" -f ./docker/php-fpm/Dockerfile .
        
    - name: Push the Docker images
      run:  |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker push "tomcraftmc/fsalist:nginx-${GITHUB_REF##*/}"
        docker push "tomcraftmc/fsalist:php-fpm-${GITHUB_REF##*/}"
