name: Docker image

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build and Push the Docker images
      run:  |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker build --pull -t "tomcraftmc/fsalist:nginx" -f ./docker/nginx/Dockerfile .
        docker push "tomcraftmc/fsalist:nginx"
        docker build --pull -t "tomcraftmc/fsalist:php-fpm" -f ./docker/php-fpm/Dockerfile .
        docker push "tomcraftmc/fsalist:php-fpm"
